apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "simple-container.fullname" . }}
  labels:
    {{- include "simple-container.labels" . | nindent 4 }}
spec:
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: ingress
    ports:
    - port: {{ .Values.service.port }}
      protocol: TCP
  - from:
    - namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: {{ .Release.Namespace }}
    ports:
    - port: {{ .Values.service.port }}
      protocol: TCP
  podSelector:
    matchLabels:
      {{- include "simple-container.selectorLabels" . | nindent 6 }}
  policyTypes:
  - Ingress
